RedeSocial/RedeSocialWeb/Controllers/AmigosController.cs
using Domain.Entidade;
using Domain.Entidade.Request;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RedeSocialWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace RedeSocialWeb.Controllers
{
    public class AmigosController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        public AmigosController(IHttpClientFactory httpClientFactory,
            IConfiguration configuration, ILogger<HomeController> logger) : base(httpClientFactory, configuration)
        {
            _logger = logger;
        }

        public async Task<IActionResult> View()
        {
            var retorno = await ApiFind<Pessoa>(this.HttpContext.Session.GetString("token"), "Pessoas/getAll");
            Pessoa usuario = new();

            foreach (var pessoa in retorno)
            {
                if (pessoa.Id.ToString() == this.HttpContext.Session.GetString("UserId"))
                {
                    usuario = pessoa;
                }
            }
            retorno.Remove(usuario);

            await CarregaDadosPessoa();
            return View(retorno);
        }
        public async Task<IActionResult> List()
        {
            var retorno = await ApiFindAllById<Pessoa>(this.HttpContext.Session.GetString("token"),
                this.HttpContext.Session.GetString("UserId"), "Pessoas/getTodosAmigos");
            await CarregaDadosPessoa();
            return View(retorno);
        }

        //buscar a pessoa por id
        [HttpGet]
        [Route("Amigos/Details/{Id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var pessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), id, "Pessoas");
            await CarregaDadosPessoa();
            return View(pessoa);
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar(Guid id)
        {
            CreateAmigo novoAmigo = new() {Id = id };
            var retorno = await ApiSaveAutorize<Pessoa>(this.HttpContext.Session.GetString("token"), novoAmigo, $"Pessoas/cadastrarAmigo/{this.HttpContext.Session.GetString("UserId")}");

            return RedirectToAction("List");
        }

        [HttpGet]
        [Route("Amigos/Deletar/{Id:guid}")]
        public async Task<IActionResult> Deletar(Guid id)
        {
            CreateAmigo novoAmigo = new() { Id = id };
            var retorno = await ApiUpdate<Pessoa>(this.HttpContext.Session.GetString("token"),
                this.HttpContext.Session.GetString("UserId"), novoAmigo, "Pessoas/removerAmigo");

            return RedirectToAction("List");
        }

        private async Task CarregaDadosPessoa()
        {
            var CargaPessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), this.HttpContext.Session.GetString("UserId"), "Pessoas");
            ViewData["ID"] = CargaPessoa.Id;
            ViewData["Email"] = CargaPessoa.Email;
            ViewData["url"] = CargaPessoa.ImagemUrlPessoa;
        }

    }
}

RedeSocial/RedeSocialWeb/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Domain.Entidade;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using RedeSocialWeb.Models;

namespace RedeSocialWeb.Controllers
{
    [Authorize]
    public class PerfilController : BaseController
    {
        private ImagemRepositorio _blobstorage;

        public PerfilController(IHttpClientFactory httpClientFactory, IConfiguration configuration) : base(httpClientFactory, configuration)
        {
            _blobstorage = new ImagemRepositorio(configuration.GetSection("Logging").GetSection("ConnectionStrings")["KeyBlobStorage"], configuration.GetSection("Logging").GetSection("ConnectionStrings")["UrlBlobStorageImagem"]);
        }

        public IConfiguration Configuration { get; }

        public async Task<IActionResult> Editar(Pessoa pessoa)
        {
            await CarregaDadosPessoa();

            return View(pessoa);
        }
        private async Task CarregaDadosPessoa()
        {
            var CargaPessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), this.HttpContext.Session.GetString("UserId"), "Pessoas");
            ViewData["ID"] = CargaPessoa.Id;
            ViewData["Email"] = CargaPessoa.Email;
            ViewData["url"] = CargaPessoa.ImagemUrlPessoa;
        }


        [HttpGet]
        [Route("Perfil/Editar/{Id:guid}")]
        public async Task<IActionResult> Editar(Guid id)
        {
            var pessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), id, "Pessoas");
            await CarregaDadosPessoa();

            return View(pessoa);
        }

        [HttpPost]
        [Route("Perfil/Editar/{Id:guid}")]
        public async Task<IActionResult> Editar(Guid id, IFormCollection collection)
        {
            var existeImagem = false;

            MemoryStream ms = new MemoryStream();
            var fileName = $"Perfil_{id}{RandomNumber()}_.png";


            foreach (var item in this.Request.Form.Files)
            {
                existeImagem = true;

                item.CopyTo(ms);

                ms.Position = 0;
            }

            Pessoa pessoa = new();

            if (existeImagem)
            {
                pessoa = new() { Nome = collection["Nome"], Sobrenome = collection["Sobrenome"], ImagemUrlPessoa = $"{fileName}" };
            }
            else
                pessoa = new() { Nome = collection["Nome"], Sobrenome = collection["Sobrenome"], ImagemUrlPessoa = "Perfil_default.png" };


            var retorno = await ApiUpdate<Pessoa>(this.HttpContext.Session.GetString("token"), id, pessoa, "Pessoas");

            if (retorno == null)
            {
                ViewData["MensagemRetorno"] = "Houve Um erro durante o post !";
            }
            else
                await _blobstorage.SaveUpdate(fileName, ms);

            return Redirect(retorno.Id.ToString());

        }
        private string RandomNumber()
        {
            Random generator = new Random();
            return generator.Next(0, 1000000).ToString("D6");
        }

        [HttpGet]
        [Route("Perfil/Excluir/{Id:guid}")]
        public async Task<IActionResult> Excluir(Guid id)
        {
            var retorno = await ApiRemove(this.HttpContext.Session.GetString("token"), id, "Pessoas");
            if (retorno.IsSuccessStatusCode)
                return RedirectToAction("Delete", "Autenticacao");

            return View();
        }

        [HttpGet]
        [Route("Perfil/PainelAdm")]
        public IActionResult PainelAdm ()
        {
                return RedirectToAction("PainelAdm", "Autenticacao");
        }


        [HttpGet]
        [Route("Perfil/ExcluirImagem/{Id:guid}")]
        public async Task<IActionResult> ExcluirImagem(Guid id)
        {
            Pessoa pessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), id, "Pessoas");
            await _blobstorage.Remove(pessoa.ImagemUrlPessoa);
            pessoa.ImagemUrlPessoa = "Perfil_default.png";
            var retorno = await ApiUpdate<Pessoa>(this.HttpContext.Session.GetString("token"), id, pessoa, "Pessoas");

            return RedirectToAction("Index", "Feed");
        }

        [HttpGet]
        [Route("Perfil/Detalhes/{Id:guid}")]
        public async Task<IActionResult> Detalhes(Guid id)
        {
            var pessoa = await ApiFindById<Pessoa>(this.HttpContext.Session.GetString("token"), id, "Pessoas");
            await CarregaDadosPessoa();

            return View(pessoa);
        }




    }
}

RedeSocial/RedeSocialWeb/Views/Shared/_Layout.cshtml
@{

    var pessoaId = ViewBag.ID;
    var pessoaEmail = ViewBag.Email;
    var pessoaImagem = ViewBag.url;

}
<!doctype html>
<html lang="pt-br" class="light-theme">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <environment include="Development">
        <link rel="icon" href="~/assets/img/favicon-32x32.png" type="image/png" />


        <!-- Bootstrap CSS -->
        <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/assets/css/bootstrap-extended.css" rel="stylesheet" />
        <link href="~/assets/css/style.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <link href="~/assets/plugins/datetimepicker/css/classic.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.time.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.date.css" rel="stylesheet" />
        <link href="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css">
    </environment>

    <environment exclude="Development">
        <link rel="icon" href="~/assets/img/favicon-32x32.png" type="image/png" />


        <!-- Bootstrap CSS -->
        <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/assets/css/bootstrap-extended.css" rel="stylesheet" />
        <link href="~/assets/css/style.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <link href="~/assets/plugins/datetimepicker/css/classic.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.time.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.date.css" rel="stylesheet" />
        <link href="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css">
    </environment>

    <title>Tracking Trip</title>
</head>

<body>


    <!--Inicio wrapper-->
    <div class="wrapper">
        <!--Inicio header-->
        <header class="top-header">
            <nav class="navbar navbar-expand gap-3">
                <div class="mobile-toggle-icon fs-3">
                    <i class="bi bi-list"></i>
                </div>

                @*<form>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Pesquisar..." aria-describedby="button-addon2">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2">Pesquisar</button>
                        </div>
                    </form>*@

                <div class="top-navbar-right ms-auto">
                    <ul class="navbar-nav align-items-center">
                        <li class="nav-item search-toggle-icon">
                            <a class="nav-link" href="#">
                                <div class="">
                                    <i class="bi bi-search"></i>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item dropdown dropdown-user-setting">
                            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-bs-toggle="dropdown">
                                <div class="user-setting d-flex align-items-center">
                                    <img src="https://paquetahomologstorage.blob.core.windows.net/imagens/@pessoaImagem" class="user-img" alt="">
                                </div>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <a class="dropdown-item" asp-controller="Perfil" asp-action="Detalhes" asp-route-id="@pessoaId">
                                        <div class="d-flex align-items-center">
                                            <img src="https://paquetahomologstorage.blob.core.windows.net/imagens/@pessoaImagem" alt="" class="rounded-circle" width="54" height="54">
                                            <div class="ms-3">
                                                <h6 class="mb-0 dropdown-user-name">@pessoaEmail</h6>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Perfil" asp-action="Detalhes" asp-route-id="@pessoaId">
                                        <div class="d-flex align-items-center">
                                            <div class=""><i class="bi bi-person-fill"></i></div>
                                            <div class="ms-3"><span>Ver o perfil</span></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Perfil" asp-action="Editar" asp-route-id="@pessoaId">
                                        <div class="d-flex align-items-center">
                                            <div class=""><i class="bi bi-gear-fill"></i></div>
                                            <div class="ms-3"><span>Editar perfil</span></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Autenticacao" asp-action="Login">
                                        <div class="d-flex align-items-center">
                                            <div class=""><i class="bi bi-lock-fill"></i></div>
                                            <div class="ms-3"><span>Sair</span></div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>
        </header>
        <!--fim header-->
        <!--incio sidebar -->
        <aside class="sidebar-wrapper" data-simplebar="true">
            <div class="sidebar-header">
                <div>
                    <img src="~/assets/img/brand-logo-2.png" class="img-fluid w-75" alt="">
                </div>

                <div class="toggle-icon ms-auto">
                    <i class="bi bi-list"></i>
                </div>
            </div>
            <!--Navegação-->
            <ul class="metismenu" id="menu">
                <li>
                    <a href="/feed/index">
                        <div class="parent-icon">
                            <i class="bi bi-file-earmark-break-fill"></i>
                        </div>
                        <div class="menu-title">Seu feed</div>
                    </a>
                </li>
                <li>
                    <a asp-controller="Feed" asp-action="TodosPosts" asp-route-id="@pessoaId">
                        <div class="fm-icon-box">
                            <i class="bi bi-file-earmark-break-fill"></i>
                        </div>
                        <div class="menu-title">Seu Posts</div>
                    </a>
                </li>

                <li class="menu-label">Sua rede</li>
                <li>
                    <a asp-controller="Amigos" asp-action="List">
                        <div class="">
                            <i class="bi bi-people-fill"></i>
                        </div>
                        <div class="menu-title">Ver Amigos</div>
                    </a>
                </li>
                <li>
                    <a asp-controller="Amigos" asp-action="View">
                        <div class="">
                            <i class="bi bi-people-fill"></i>
                        </div>
                        <div class="menu-title">Pessoas da Rede</div>
                    </a>
                </li>

                @*<li class="menu-label">Perfil</li>
                    <li>

                            <div class="menu-title"> <i class="bi bi-person-lines-fill"></i> Opções de perfil</div>

                        <ul>
                            <li>
                                <a href="/perfil/perfilusuario"><i class="bi bi-circle"></i>Ver perfil</a>
                            </li>
                            <li>
                                <a href="/perfil/editarperfil"><i class="bi bi-circle"></i>Editar perfil</a>
                            </li>
                            <li>
                                <a href="/perfil/excluirconta"><i class="bi bi-circle"></i>Excluir conta</a>
                            </li>
                        </ul>
                    </li>*@

                @*<li class="menu-label">Trilhas</li>
                    <li>


                            <div class="menu-title"><i class="bi bi-compass"></i> Opções de Trilhas</div>

                        <ul>
                            <li>
                                <a href="/trilhas/trilhasconfirmadas"><i class="bi bi-circle"></i>Trilhas confirmadas</a>
                            </li>
                            <li>
                                <a href="/trilhas/criartrilha"><i class="bi bi-circle"></i>Criar trilha</a>
                            </li>
                            <li>
                                <a href="/trilhas/listartrilhas"><i class="bi bi-circle"></i>Editar trilha</a>
                            </li>
                            <li>
                                <a href="/trilhas/listartrilhas"><i class="bi bi-circle"></i>Excluir trilha</a>
                            </li>
                        </ul>
                    </li>*@
            </ul>
            <!--fim navegação-->
        </aside>

        <!--fim sidebar -->
        <!--inicio content-->
        <div class="bg-surface">
            @RenderBody()
        </div>


        <!--fim main-->

    </div>
    <!--fim wrapper-->

    <environment include="Development">
        <script src="~/assets/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/js/jquery.min.js"></script>
        <script src="~/assets/js/app.js"></script>
        <!--datetimepicker e  file-uploader-->
        @*<script src="~/assets/plugins/datetimepicker/js/picker.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.time.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.date.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/moment.min.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js"></script>
        <script src="~/assets/plugins/fancy-file-uploader/jquery.fileupload.js"></script>
        <script src="~/assets/plugins/fancy-file-uploader/jquery.fancy-fileupload.js"></script>
        <script src="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.js"></script>
        <script src="~/assets/js/form-file-upload.js"></script>
        <script src="~/assets/js/form-date-time-pickes.js"></script>*@

    </environment>
    <environment exclude="Development">
        <script src="~/assets/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/js/jquery.min.js"></script>
        <script src="~/assets/js/app.js"></script>
        <!--datetimepicker e  file-uploader-->
        @*<script src="~/assets/plugins/datetimepicker/js/picker.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.time.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.date.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/moment.min.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js"></script>
        <script src="~/assets/plugins/fancy-file-uploader/jquery.fileupload.js"></script>
        <script src="~/assets/plugins/fancy-file-uploader/jquery.fancy-fileupload.js"></script>
        <script src="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.js"></script>
        <script src="~/assets/js/form-file-upload.js"></script>
        <script src="~/assets/js/form-date-time-pickes.js"></script>*@
    </environment>



    @RenderSection("scripts", required: false)
</body>

</html>

RedeSocial/RedeSocialWeb/Views/Shared/_LayoutDeslogado.cshtml
<!doctype html>

<html lang="pt-br" class="light-theme">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <environment include="Development">
        <link rel="icon" href="~/assets/img/favicon-32x32.png" type="image/png" />


        <!-- Bootstrap CSS -->
        <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/assets/css/bootstrap-extended.css" rel="stylesheet" />
        <link href="~/assets/css/style.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <link href="~/assets/plugins/datetimepicker/css/classic.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.time.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.date.css" rel="stylesheet" />
        <link href="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css"
              asp-fallback-href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>

    <environment exclude="Development">
        <link rel="icon" href="~/assets/img/favicon-32x32.png" type="image/png" />


        <!-- Bootstrap CSS -->
        <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/assets/css/bootstrap-extended.css" rel="stylesheet" />
        <link href="~/assets/css/style.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <link href="~/assets/plugins/datetimepicker/css/classic.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.time.css" rel="stylesheet" />
        <link href="~/assets/plugins/datetimepicker/css/classic.date.css" rel="stylesheet" />
        <link href="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css"
              asp-fallback-href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>

    <title>Tracking Trip</title>
</head>

<body>
    <!--Inicio wrapper-->
    <div class="wrapper">
        <!--fim sidebar -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-white rounded-0 border-bottom">
                <div class="container">
                    <div class="col-12 p-0 flex-column d-flex align-items-center justify-content-center my-3">
                        <!-- logo -->
                        <a class="navbar-brand" href="#"><img src="~/assets/img/brand-logo-2.png" width="400" alt="" /></a>
                        <!-- fim da logo -->
                    </div>
                </div>
            </nav>
        </header>
        <!--inicio content-->
        <div class="bg-surface">
            <div class="wrapper">
                @RenderBody()
            </div>
            <div>

            </div>
        </div>
        <footer class="bg-white border-top p-3 text-center fixed-bottom">
            <p class="mb-0">2021 © Tracking Trip - Todos os Direitos Reservados</p>
        </footer>

        <!--fim main-->

    </div>
    <!--fim wrapper-->
    <environment include="Development">
        <script src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-test="window.jQuery"></script>
        <script src="~/assets/js/jquery.min.js" asp-fallback-src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-test="window.jQuery"></script>
        <script src="~/assets/js/app.js" asp-fallback-src="~/assets/js/app.js" asp-fallback-test="window.jQuery"></script>
        <!--datetimepicker e  file-uploader-->
        @*<script src="~/assets/plugins/datetimepicker/js/picker.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.time.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.date.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/moment.min.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js" asp-fallback-src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js" asp-fallback-test="window.jQuery"></script>*@
        @*<script src="~/assets/plugins/fancy-file-uploader/jquery.fileupload.js"></script>
        <script src="~/assets/plugins/fancy-file-uploader/jquery.fancy-fileupload.js"></script>
        <script src="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.js"></script>
        <script src="~/assets/js/form-file-upload.js"></script>
        <script src="~/assets/js/form-date-time-pickes.js"></script>*@

    </environment>
    <environment exclude="Development">
        <script src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-test="window.jQuery"></script>
        <script src="~/assets/js/jquery.min.js" asp-fallback-src="~/assets/js/bootstrap.bundle.min.js" asp-fallback-test="window.jQuery"></script>
        <script src="~/assets/js/app.js" asp-fallback-src="~/assets/js/app.js" asp-fallback-test="window.jQuery"></script>
        <!--datetimepicker e  file-uploader-->
        @*<script src="~/assets/plugins/datetimepicker/js/picker.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.time.js"></script>
        <script src="~/assets/plugins/datetimepicker/js/picker.date.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/moment.min.js"></script>
        <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js" asp-fallback-src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.min.js" asp-fallback-test="window.jQuery"></script>*@
        @*<script src="~/assets/plugins/fancy-file-uploader/jquery.fileupload.js"
                asp-fallback-src="~/assets/plugins/fancy-file-uploader/jquery.fileupload.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>*@
        @*<script src="~/assets/plugins/fancy-file-uploader/jquery.fancy-fileupload.js"></script>
        <script src="~/assets/plugins/Drag-And-Drop/dist/imageuploadify.min.js"></script>
        <script src="~/assets/js/form-file-upload.js"></script>
        <script src="~/assets/js/form-date-time-pickes.js"></script>*@
    </environment>

    @RenderSection("scripts", required: false)

</body>

</html>